# Generated by Django 3.2.25 on 2024-11-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=30)),
                ('facility_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('task', models.CharField(max_length=100)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='database.facility')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.AddField(
            model_name='person',
            name='facility_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='database.facility'),
        ),
        migrations.AddField(
            model_name='person',
            name='group_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='database.group'),
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='database.person')),
            ],
            options={
                'unique_together': {('person', 'date')},
            },
        ),
        migrations.CreateModel(
            name='groupleader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leader', to='database.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leaderships', to='database.person')),
            ],
            options={
                'unique_together': {('group_id', 'person_id')},
            },
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.IntegerField()),
                ('date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='database.person')),
            ],
            options={
                'unique_together': {('person', 'date')},
            },
        ),
        migrations.CreateModel(
            name='facility_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_manager', to='database.facility')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_managements', to='database.person')),
            ],
            options={
                'unique_together': {('facility_id', 'person_id')},
            },
        ),
    ]
