# Generated by Django 3.2.25 on 2024-11-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20241117_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='facility_manager',
            options={'verbose_name': 'Facility manager', 'verbose_name_plural': 'Facility managers'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Food order', 'verbose_name_plural': 'Food orders'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='groupleader',
            options={'verbose_name': 'Group leader', 'verbose_name_plural': 'Group leaders'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
