# Generated by Django 3.2.25 on 2024-11-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
