# Generated by Django 3.2.25 on 2024-11-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20241122_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='qr_code',
        ),
    ]
