# Generated by Django 3.2.25 on 2024-11-27 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0010_remove_person_qr_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='food_for_day',
        ),
        migrations.AddField(
            model_name='food',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupleader',
            name='expires',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='facility_manager',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_manager', to='database.facility'),
        ),
        migrations.AlterField(
            model_name='facility_manager',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_managements', to='database.person'),
        ),
        migrations.AlterField(
            model_name='food',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food', to='database.person'),
        ),
        migrations.AlterField(
            model_name='group',
            name='facility_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='database.facility'),
        ),
        migrations.AlterField(
            model_name='groupleader',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_leader', to='database.group'),
        ),
        migrations.AlterField(
            model_name='groupleader',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_leaderships', to='database.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='group_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='database.group'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
