# Generated by Django 3.2.25 on 2025-01-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20241127_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='food',
            name='food',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
