# Generated by Django 5.1.4 on 2025-01-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_pdfdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(upload_to='menu/'),
        ),
    ]
