# Generated by Django 5.1.4 on 2025-01-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_pdfdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_location',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
